Feature/jc 542 anime list
saritasa-nest/camp-js-2023-roman-simernin pull request #10
Opened 2023-07-23 15:43 UTC by shalomich

2023-07-24 04:48 UTC, golovachev-yaroslav approved these changes

2023-07-25 03:16 UTC, dbitkovski requested changes

2023-07-25 03:16 UTC, dbitkovski commented on apps/angular/src/app/app-routing.module.ts
> +	},
If you use routing you need to care about the case when use types unexisting route.
https://angular.io/guide/router-tutorial-toh#define-a-wildcard-route

2023-07-25 03:16 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.css
> +@import "../../../../../../../libs/theme/src/variables.css";
If I'm not mistaken there is a main styles file. You should import it there and after that variables will be available in every style file

2023-07-25 03:16 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.html
> +          {{animePreview.airedStartDate.toLocaleDateString()}} </td>
That's okay to use javascript `Date` methods but usually we prefer angular pipes. It has built-in pipe to format dates https://angular.io/api/common/DatePipe

2023-07-25 03:16 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +	public readonly displayedAnimeTableColumns: string[] = [
If the array is not supposed to be changed, you can make it readonly with `readonly string[]` type

2023-07-25 03:16 UTC, dbitkovski commented on apps/angular/src/core/interceptors/apiKeyHeaderInterceptor.ts
> +	providedIn: 'root',
You don't need to use `providedIn` for interceptors because you register them manually

2023-07-25 03:16 UTC, dbitkovski commented on apps/angular/src/core/interceptors/apiKeyHeaderInterceptor.ts
> +		request.headers.append('Api-Key', environment.apiKey);
Probably I haven't written interceptor for a long time but as I remember we need to clone request object to make it work predictable. Also, angular docs mentions it as well
https://angular.io/guide/http-intercept-requests-and-responses#modify-a-request-body

2023-07-25 03:16 UTC, dbitkovski commented on libs/core/models/animePreview.ts
> +export class AnimePreview {
Never thought about `Preview` suffix, cool. Are you sure there will be an extended model though? Maybe we need to make it `Anime` instead?

2023-07-25 03:16 UTC, dbitkovski commented on apps/angular/src/core/interceptors/apiKeyHeaderInterceptor.ts
> +	providedIn: 'root',
Okay, I see you don't use `HTTP_ITNERCEPTORS` injection token. That's strange, it should not work.
https://angular.io/guide/http-intercept-requests-and-responses#provide-the-interceptor

2023-07-25 03:58 UTC, golovachev-yaroslav approved these changes

2023-07-26 10:42 UTC, shalomich commented on libs/core/models/animePreview.ts
> +export class AnimePreview {
@dbitkovski  We use Preview and Details suffixes in .net projects to splits DTO for search and getting by id accordingly. Now I don't know if we will make a separate page for anime. So I rename it to Anime but if we will need anime details I will want to return back this prefix

2023-07-26 11:17 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.css
> +@import "../../../../../../../libs/theme/src/variables.css";
You are sure, variables is already imported in index.css so import in component is useless

2023-07-26 15:00 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/core/services/animeService.ts
> +	public searchAnime(): Observable<Anime[]> {
I think the main purpose of this method is to get anime list, not exactly search for anime, since you don't always pass the search parameter. Consider naming it something like `getList`. I guess it will sound more correct)

2023-07-28 08:15 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/core/services/apiUriBuilder.ts
> +	public buildSearchAnimeUri(): string {
Can we update the name here too? 🌚

2023-07-28 08:15 UTC, gevorg-gevorgyan-saritasa commented on libs/core/models/anime.ts
> +export class Anime {
I think there is no point to use `class` for Anime model, since you use it only for naming a type, and don't provide additional logic (and I'm not sure that you will add something in the future). So maybe `interface` is enough, what do you think?

2023-07-28 08:15 UTC, gevorg-gevorgyan-saritasa commented on libs/core/mappers/anime.mapper.ts
> +			status: dto.status.replace(/_/g, ' '),
Since `status` can be represented as one of the constant values which you know, I would suggest you to consider creating a type (for example, using `enum`)

2023-07-28 08:20 UTC, dbitkovski approved these changes

2023-07-28 08:32 UTC, shalomich commented on libs/core/mappers/anime.mapper.ts
> +			status: dto.status.replace(/_/g, ' '),
I think we don't need enum now, because this value is ony displayed in table and isn't used in conditions for business logic. It will maybe do that in next task

2023-07-28 09:09 UTC, gevorg-gevorgyan-saritasa approved these changes

2023-07-28 09:11 UTC, merged