Feature/jc 543 anime management
saritasa-nest/camp-js-2023-roman-simernin pull request #11
Opened 2023-08-22 20:34 UTC by shalomich

2023-08-26 20:13 UTC, dmitrymaslov13 requested changes

2023-08-26 20:13 UTC, dmitrymaslov13 commented on libs/core/utils/nameof.ts
> +export const nameofFactory = <T>() => (fieldName: keyof T) => fieldName;
For omit not object types

```suggestion
export const nameofFactory = <T extends Record<string, any>>() => (fieldName: keyof T) => fieldName;
```

2023-08-26 20:13 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +		});
It bit broke my brain.

The problem is that we have multiple sources of truth.
One of them is in the service, the second is in the component.

Do we really have no way to leave the parameters only in the service?

2023-08-26 20:13 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +			);
I think there is no need to create a separate field with this logic that we only subscribe to

Let's create simlar method and move it in `ngOnInit`.

```ts
private subscribeToFiltersChanges(): void {
	this.animeFiltersFormGroup.valueChanges
			.pipe(
				map(({ search, animeTypes }) => this.animeParametersService.setFilters(search ?? '', animeTypes ?? [])),
				tap(parameters => this.paginatorSettings$.next(parameters)),
				takeUntilDestroyed(),
			).subscribe();
}
```

This will simplify the code in the following places
1) We immediately see where the subscription is taking place, and that this subscription is being managed.
2) We isolate the logic in a specific method, which makes it easier to read the method where it is used
3) We remove extra fields in class.

2023-08-27 12:27 UTC, shalomich commented on apps/angular/src/core/services/anime-parameters.service.ts
> +		private readonly activatedRoute: ActivatedRoute,
I know about. What way for injection do you use in real projects: constructor or inject function?

2023-08-27 12:30 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime-parameters.service.ts
> +		private readonly activatedRoute: ActivatedRoute,
Cool! On new projects, we try to stick to the function approach.

2023-08-27 12:37 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +	public readonly animeTypes: string[] = ['TV', 'OVA', 'Movie', 'Special', 'ONA', 'Music', 'Unknown'];
I am not sure enum can resolve probability of missing if I understand you clearly. We use enum for business logic when want to have condition according its value. But this is not the case here.

2023-08-27 12:51 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +	public readonly animeTypes: string[] = ['TV', 'OVA', 'Movie', 'Special', 'ONA', 'Music', 'Unknown'];
I understand, I did not see your past reviews.
I did not know that you have a server type in string format.

if I'm not mistaken on the server it is an enum. At least it was like that for the other campers

2023-08-27 12:52 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +	public readonly animeTypes: string[] = ['TV', 'OVA', 'Movie', 'Special', 'ONA', 'Music', 'Unknown'];
```suggestion
	public readonly animeTypes: readonly string[] = ['TV', 'OVA', 'Movie', 'Special', 'ONA', 'Music', 'Unknown'];
```

2023-08-27 12:57 UTC, shalomich commented on libs/core/utils/nameof.ts
> +export const nameofFactory = <T>() => (fieldName: keyof T) => fieldName;
Linter warn me about `any` using. Can I make T extended object? It works for my case.

2023-08-27 13:17 UTC, dmitrymaslov13 commented on libs/core/utils/nameof.ts
> +export const nameofFactory = <T>() => (fieldName: keyof T) => fieldName;
Yes, in this case you can use `object`

2023-08-27 13:21 UTC, dmitrymaslov13 commented on libs/core/utils/nameof.ts
> +export const nameofFactory = <T>() => (fieldName: keyof T) => fieldName;
Just for you know (it not about your case, but about types), i suggested `Record<string, any>` because it analog object, but with ability to access fields

in `object` case we will get error

see [example](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgLhgJQKagE4BMA80MCWYA5gDTxgCeAfDALwwDeMAUDDAGYGoA2WSAcgAWvHiAGkWAXxYs4AOi68sAblmhIsAEZIQWgFbpYDRm07c+gkTzEDpsrfOtigA)

2023-08-28 01:16 UTC, kristinaSvobodinaSaritasa commented
https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/82072005/a5b2d1c1-eff9-4d69-853d-24c3020a88db

Please fix issue with pagination

2023-08-28 01:18 UTC, kristinaSvobodinaSaritasa commented
<img width="1430" alt="Screenshot 2023-08-28 at 08 18 05" src="https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/82072005/d319b691-382e-46ef-af1d-afe80257f076">
Please, check the error in console.

2023-08-28 01:32 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.html
> +      <input matInput [formControl]="animeFiltersFormGroup.controls.search">
```suggestion
      <input matInput formControlName="search">
```

2023-08-28 06:55 UTC, shalomich commented on apps/angular/src/core/services/anime-parameters.service.ts
> +		private readonly activatedRoute: ActivatedRoute,
So I will do with this way in next PRs

2023-08-28 06:59 UTC, shalomich commented on libs/core/utils/nameof.ts
> +export const nameofFactory = <T>() => (fieldName: keyof T) => fieldName;
Got it

2023-08-28 07:22 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +	protected readonly animeTypes: readonly string[] = ['TV', 'OVA', 'Movie', 'Special', 'ONA', 'Music', 'Unknown'];
Let's create an `enum` for Anime Type. For example:
```ruby
export enum AnimeType {
	TV = 'Tv',
}

export namespace AnimeType {
        /** Return enum values here. */
	export function toArray() {
		return enumToArray(AnimeType);
	}
}
```
You can create more func like `toReadable()` if needed

2023-08-28 07:22 UTC, LocTran-saritasa commented on apps/angular/src/core/services/anime-parameters.service.ts
> +	 */
```suggestion
	/** Anime parameters. */
```

2023-08-28 07:22 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.html
> +			<mat-select [formControl]="animeFiltersFormGroup.controls.animeTypes" multiple>
```suggestion
			<mat-select formControlName="animeTypes" multiple>
```

2023-08-28 07:42 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +	protected readonly animeTypes: readonly string[] = ['TV', 'OVA', 'Movie', 'Special', 'ONA', 'Music', 'Unknown'];
What do you think about my comment for this https://github.com/saritasa-nest/camp-js-2023-roman-simernin/pull/11#discussion_r1306658232

2023-08-28 08:29 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +	protected readonly animeTypes: readonly string[] = ['TV', 'OVA', 'Movie', 'Special', 'ONA', 'Music', 'Unknown'];
Hmm, I think you will need to change it to `enum` anyway when you integrate API for filtering. You need to map your `enum` to `enumDto` from BE.
In addition, it will create a `source of truth` to help your code more maintainable
You should find some articles to read about it :wink:

2023-08-30 08:51 UTC, andrey-gazzaev requested changes

2023-08-30 08:51 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.html
> +				<mat-option *ngFor="let animeType of animeTypes;" [value]="animeType">{{animeType}}</mat-option>
Don't forget to add `trackBy`.

2023-08-30 08:51 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.html
> +              alt="{{ animePreview.englishTitle }}" />
I don't think the alternate image description makes sense since you are using a description from a different column. You can come up with a more meaningful description or remove it altogether.

2023-08-30 08:51 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +	providers: [AnimeParametersService],
Let's add an `onPush` strategy

2023-08-30 08:51 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +		animeTypes: FormControl<readonly string[] | null>;
```suggestion
		animeTypes: FormControl<string[] | null>;
```

We don't normally describe outgoing arrays as `readonly`. In the future, this may cause some difficulties when you do want to change these arrays.

2023-08-30 08:51 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +			sortingDirection = sortingEvent.direction as SortingDirection;
In this case, there is a leaking abstraction. The `sortingEvent.direction` and `SortingDirection`  are at different abstraction layers.

2023-08-30 08:51 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime-parameters.service.ts
> +	public readonly availablePageSizes: readonly number[] = [5, 10, 25];
```suggestion
	public readonly availablePageSizes = [5, 10, 25] as const;
```

2023-08-30 08:51 UTC, andrey-gazzaev commented on libs/core/mappers/anime-type.mapper.ts
> +		readonly animeTypeDto: AnimeTypeDto;
```suggestion
		/** Anime type model. */
		readonly model: AnimeType;

		/** Anime type dto. */
		readonly dto: AnimeTypeDto;
```
It will be clear from the context which entity `dto` and `model` refer to.

2023-08-30 08:51 UTC, andrey-gazzaev commented on libs/core/models/pagination.ts
> +	readonly results: readonly T[];
```suggestion
	readonly results: T[];
```

2023-08-30 08:51 UTC, andrey-gazzaev commented on libs/core/models/sorting-parameters.ts
> +	readonly sortingDirection: SortingDirection | null;
```suggestion
	readonly field: T | null;

	/** Sorting direction. */
	readonly direction: SortingDirection | null;
```

same

2023-08-30 08:51 UTC, andrey-gazzaev commented on libs/core/utils/enum.utils.ts
> +		return Object.values(enumeration);
As you may have noticed `enum` is syntactic sugar. When translating it to js it will be an object. That's why you can call `enum` and `namespace` by the same name. Therefore it would be good to check that the array of values contains only the expected values of the object.

2023-08-30 08:51 UTC, andrey-gazzaev commented on libs/core/mappers/anime-type.mapper.ts
> +	];
Cool!

2023-08-30 08:51 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime-parameters.service.ts
> +		const paginationParameters = this.resetedPagination;
It seems that you do not work with this variable in the future, so it does not make sense to allocate a variable for it. Use the value directly

2023-08-30 16:02 UTC, shalomich commented on apps/angular/src/core/services/anime-parameters.service.ts
> +	public readonly availablePageSizes: readonly number[] = [5, 10, 25];
I have an error
<img width="567" alt="image" src="https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/75197645/b3293d36-e807-4339-b34e-3399542f5a1a">

2023-08-30 16:15 UTC, timofei-maximov-saritasa approved these changes

2023-08-30 16:15 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.html
> +          (page)="handlePaginationParametersChange(($event))"
Is it a typo?

```suggestion
          (page)="handlePaginationParametersChange($event)"
```

2023-08-30 16:15 UTC, timofei-maximov-saritasa commented on libs/core/utils/enum.utils.ts
> +		* Convert enum to string array.
```suggestion
	* Convert enum to string array.
```

2023-08-30 16:15 UTC, timofei-maximov-saritasa commented on libs/core/utils/enum.utils.ts
> +		* @param enumValueAsString - Enum value as string.
```suggestion
	* Convert enum to string array.
	* @param enumValueAsString - Enum value as string.
```

2023-08-31 06:05 UTC, andrey-gazzaev approved these changes

2023-08-31 06:05 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.ts
> +		const pageNumber: number = paginationEvent.pageIndex + 1;
```suggestion
		const pageNumber = paginationEvent.pageIndex + 1;
```

In such cases you don't need to describe the type, TS will determine it itself

2023-08-31 06:05 UTC, andrey-gazzaev commented on libs/core/models/anime.ts
> +/** Anime type dto. */
```suggestion
/** Anime type. */
```

2023-08-31 07:15 UTC, danilkukryakov requested changes

2023-08-31 07:15 UTC, danilkukryakov commented on libs/core/mappers/anime-parameters.mapper.ts
> +			throw new Error('There is no sorting for this field.');
Please, be careful with throwing errors in a frontend application.
Not all frameworks have error boundaries. so even a small error can break the whole app.
A good alternative is a `console.warn`. In this case we will notify the developer about an error but we will implement fallback behaviour so app is working fine.

2023-08-31 07:15 UTC, danilkukryakov commented on libs/core/models/pagination.ts
> +	readonly results: T[];
Prefer to use `readonly` arrays where possible.
```suggestion
	readonly results: readonly T[];
```

2023-08-31 07:15 UTC, danilkukryakov commented on apps/angular/src/core/services/anime-parameters.service.ts
> +			pageNumber : this.defaultPaginationParameters.pageNumber;
```suggestion
		const validPageNumber = Math.max(pageNumber, this.defaultPaginationParameters.pageNumber);
```

2023-08-31 07:15 UTC, danilkukryakov commented on apps/angular/src/core/services/anime-service.ts
> +				})),
Most likely we will have other entities with pagination in the future. Let's create a reusable mapper to map 'PaginationDto' to 'Pagination'.

2023-08-31 07:15 UTC, danilkukryakov commented on libs/core/mappers/anime-parameters.mapper.ts
> +				.toString(),
In the JSDoc there is a comment:
> Types are separated by comma.

We can make our intentions more explicit by using `.join` instead of '.toString':
```suggestion
			type__in: model.animeTypes
				.map(animeTypeModel => AnimeTypeMapper.toDto(animeTypeModel))
				.join(','),
```

2023-08-31 07:15 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.html
> +            <img alt="" [src]="animePreview.imageUrl" class="anime-table__cell-image"/>
Please, provide 'alt' attribute to make our UI more accessible.

2023-08-31 07:39 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.html
> +            <img alt="" [src]="animePreview.imageUrl" class="anime-table__cell-image"/>
https://github.com/saritasa-nest/camp-js-2023-roman-simernin/pull/11#discussion_r1309893467
https://github.com/saritasa-nest/camp-js-2023-roman-simernin/pull/11#discussion_r1311129492

2023-08-31 08:26 UTC, danilkukryakov commented on libs/core/models/pagination.ts
> +	readonly results: T[];
Why though?
According to our [wiki](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#promote-immutability) we should as much as possible to promote immutability.
So if `readonly` doesn't break things it's better to use it.
So I think previous comment was incorrect. It was a good idea to ask about clarification and motivation behind omitting `readonly`.

2023-08-31 08:34 UTC, danilkukryakov commented on apps/angular/src/core/services/anime-parameters.service.ts
> +		const pageNumber = Number.parseInt(paramMap.get(nameof('pageNumber')) ?? '', 10);
Interesting C# inspired solution.
However, I suppose this solution is an over-engineering. It's a too complex solution to do a simple thing.
We can use Router `queryParams` instead of 'queryParamsMap'. It will allow us to provide our custom type to it.
It will look like this:
```ts
type AnimePageQueryParams = Partial<Record<keyof AnimeParameters, string>>;

export class AnimeParametersService {
	public constructor(
		private readonly router: Router,
		private readonly activatedRoute: ActivatedRoute,
	) {
		this.animeParameters$ = this.activatedRoute.queryParams.pipe(
			map(params => this.parseAnimeParameters(params)),
		);
	}

	public get animeParameters(): AnimeParameters {
		return this.parseAnimeParameters(this.activatedRoute.snapshot.queryParams);
	}

	private parseAnimeParameters(params: AnimePageQueryParams): AnimeParameters {
		const pageSize = Number.parseInt(params.pageSize ?? '', 10);
		const pageNumber = Number.parseInt(params.pageNumber ?? '', 10);
		// 
	}
}
```

2023-08-31 13:23 UTC, danilkukryakov approved these changes
You've done great job on code adjustments and refactoring 👍 
You can merge this PR after you fix the last comments. If you have any questions feel free to ping me in Slack.

2023-08-31 13:23 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime.module.ts
> +		ReactiveFormsModule,
As far as I can see you don't use template driven forms in your app.
So we can remove 'FormsModule' import as it's redundant for reactive forms.
```suggestion
		ReactiveFormsModule,
```

You can read this [article](https://blog.angular-university.io/introduction-to-angular-2-forms-template-driven-vs-model-driven/) to get more details about their differences.

2023-08-31 13:23 UTC, danilkukryakov commented on apps/angular/src/core/services/anime-parameters.service.ts
> +type AnimePageQueryParams = Partial<Record<keyof AnimeParameters, string | null>>;
'null' in type is redundant here because we have `Partial` type wrapper.
```suggestion
type AnimePageQueryParams = Partial<Record<keyof AnimeParameters, string>>;
```

2023-08-31 13:23 UTC, danilkukryakov commented on apps/angular/src/core/services/anime-parameters.service.ts
> +type AnimePageQueryParams = Partial<Record<keyof AnimeParameters, string | null>>;
I know we have to add 'null' to use it with 'SortingParameters'.
However, I suppose we can adjust 'SortingParameters' type instead. It looks like 'null' inside the 'SortingParameters' is redundant. 
For instance, object below doesn't make sense to me:
```ts
const sortParams: SortingParameters = {
  filed: null,
  direction: SortingDirection.Ascending,
}
```

I suppose, either we should have both properties inside 'SortingParameters' or the params itself should be empty.
Let's try to refactor it.

2023-08-31 13:23 UTC, danilkukryakov commented on libs/core/dtos/anime-parameters.dto.ts
> +}
Most likely we will need Pagination and Sort parameters in other entities with pagination/sorting.
So let's create new separate interfaces for Pagination and Sorting properties.
```ts
export interface PaginationParamsDto {
	readonly limit: number;
	readonly offset: number;
}

export interface SortParamsDto {
	readonly ordering: string;
}


// anime-parameters.dto.ts
interface AnimeFiltersDto {
	readonly type__in: string;
	readonly search: string;
}

export type AnimeParametersDto = AnimeFiltersDto & PaginationParamsDto & SortParamsDto;
```

2023-08-31 13:23 UTC, danilkukryakov commented on libs/core/utils/nameof.ts
> +export const nameofFactory = <T extends object>() => (fieldName: keyof T) => fieldName;
We don't use this utility anymore. Let's delete it.

2023-08-31 16:20 UTC, merged