Feature/jc 548 authorization
saritasa-nest/camp-js-2023-roman-simernin pull request #12
Opened 2023-08-28 18:59 UTC by shalomich

2023-09-01 05:11 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/login/login.component.ts
> +			server: apiError.errorMessages.join(' '),
The use of terms like `server`, `api`, `http` at the UI layer is confusing as to why the UI knows anything about the response layer

2023-09-01 05:11 UTC, andrey-gazzaev commented on apps/angular/src/core/services/tokens-storage.service.ts
> +		this.tokens = tokens;
What is the reason for duplicate tokens in `runtime` and `localStorage`?

2023-09-01 05:11 UTC, andrey-gazzaev commented on apps/angular/src/core/utils/application-validators.ts
> +			const minLength = 8;
Let's make this variable a parameter

2023-09-01 05:11 UTC, andrey-gazzaev commented on apps/angular/src/core/utils/application-validators.ts
> +	export function passwordMinLength(): ValidatorFn {
I think this validation can become general for all form components

2023-09-01 05:11 UTC, andrey-gazzaev commented on apps/angular/src/core/utils/rxjs/catch-api-error.ts
> +	return response.error.errors instanceof Array &&
`instanceof Array` is not a reliable mechanism. In short, we cannot guarantee what value will be returned depending on the system the application is running on. Let's use `isArray`.

https://stackoverflow.com/questions/22289727/difference-between-using-array-isarray-and-instanceof-array#:~:text=on%20here.-,Which%20of%20these%20two%20is%20the%20preferred%20solution%3F,iframes/window%2C%20Array.isArray()%20would%20be%20more%20robust%20solution.,-Make%20sure%20to

2023-09-01 07:55 UTC, andrey-gazzaev commented on apps/angular/src/core/services/tokens-storage.service.ts
> +		this.tokens = tokens;
This can cause data to become unsynchronized. I think we should stick to a single data source. While this is unlikely with tokens, it could be a problem with other similar data. For example, if we have to store user id's etc. We may use an external store instead of local storage, in which case we can't guarantee that the value will not be changed.

2023-09-04 03:24 UTC, andrey-gazzaev approved these changes

2023-09-04 03:24 UTC, andrey-gazzaev commented on apps/angular/src/core/utils/rxjs/catch-api-error.ts
> +			const apiErrorDto = response.error as ApiErrorDto;
Instead of casting, you could make the guard.
For example:
```ts
function isApiErrorDto(error: unknown): error is ApiErrorDto {
    // some condition...
}
```
https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

2023-09-04 03:24 UTC, andrey-gazzaev commented on libs/core/dtos/auth/refresh-tokens.dto.ts
> +}
You can use `Pick<TokensDto, 'refresh'>`

2023-09-04 03:24 UTC, andrey-gazzaev commented on libs/core/mappers/auth/login.model.mapper.ts
> +	export function ToDto(model: LoginModel): LoginDto {
```suggestion
	export function toDto(model: LoginModel): LoginDto {
```

2023-09-04 03:24 UTC, andrey-gazzaev commented on libs/core/mappers/auth/registration.model.mapper.ts
> +	export function ToDto(model: RegistrationModel): RegistrationDto {
same

2023-09-04 03:24 UTC, andrey-gazzaev commented on libs/core/mappers/auth/login.model.mapper.ts
> +import { LoginDto } from '../../dtos/auth/login.dto';
Let's change the name of the file to `login-model.mapper.ts`

2023-09-04 03:24 UTC, andrey-gazzaev commented on libs/core/models/auth/registration.model.ts
> +export interface RegistrationModel {
The postfix is redundant here. It's already clear that it's a model
```suggestion
export interface Registration {
```

2023-09-05 06:24 UTC, timofei-maximov-saritasa approved these changes

2023-09-05 06:24 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +			tap(_ => this.router.navigate([''])),
```suggestion
			tap(() => this.router.navigate([''])),
```

2023-09-05 11:51 UTC, shalomich commented on libs/core/dtos/auth/refresh-tokens.dto.ts
> +}
I am not sure I need to use it here because these are independent DTOs.

2023-09-06 06:59 UTC, danilkukryakov requested changes

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/app.component.html
> +    <header class="app-header">
By the way, if you follow some guidelines then you code is fine.
For instance, [opinionated-angular](https://github.com/Gbuomprisco/opinionated-angular) suggests some rules for increasing templates readability. It has a rule related to 'ng-container' and structural directives.
> Add structural directives only to ng-container elements

This is not a recommendation but rather an option to consider.
To be honest, I found [attributes order rule](https://github.com/Gbuomprisco/opinionated-angular#rules-for-writing-html-tags) from opinionated-angular the most useful in practice. I'm not sure why we don't have it in our Angular boilerplate though. Anyway, we use such convention (and there is a linter rule for it) on several projects and it greatly increases code readability. So it's up to you whether you want to use it or not.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/app.component.html
>  <router-outlet></router-outlet>
Let's use self closing tags for Angular components where possible:
```suggestion
<router-outlet />
```

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-routing.module.ts
> +export class AnimeRoutingModule { }
Please, adjust documentation for this routing module.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/auth-routing.module.ts
> +		redirectTo: '/auth/login',
If I'm not mistaken 'redirectTo' will work in the scope of current routing module. So we'd rather do something like this:
```suggestion
		redirectTo: 'login',
```

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/auth-routing.module.ts
> +];
Wildcard routes is always a good thing to have. You can read about them in Angular [docs](https://angular.io/guide/router#setting-up-wildcard-routes).
We prefer to add such routes in every routing module. So user is redirected to default page if URL in the browser address bar was incorrect.
Be careful though, spend some time on additional testing to avoid unreachable routes or cycle redirects.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/login/login.component.html
> +<div class="login">
We can remove this 'div' and apply it's styles directly to ':host' element:
```css
/* login.component.css */
:host {
  display: flex;
  justify-content: center;
}
```

```html
<!-- login.component.html -->
<form class="form">
  <!-- ... -->
</form>
```

It will help us to reduce code nesting and thus increase code readability.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/login/login.component.spec.ts
Andrey already mentioned it but you marked his comment as 'Resolved'.
Our Angular projects are configured to generate tests automatically. By default a simple test is created by CLI for each component. The test simply checks wether component can be created.
This test doesn't give us any useful information about the component because we can rely on TypeScript compilation errors to be sure that component is valid/invalid.

In the JSCamp task you don't have any requirements related to tests. So it's up to you whether you want to write them or not. If you don't have much time then I'd suggest you to focus on the features first and write tests at the end. For now we can remove tests completely so they don't distract us (you and code reviewers).

If you want to see some examples of simple tests then you may start with our Angular boilerplate. For instance, [login.component.spec.ts](https://github.com/saritasa-nest/saritasa-frontend-boilerplate-angular/blob/develop/projects/web/src/app/features/auth/login/login.component.spec.ts) has an example of unit tests for login form.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/login/login.component.ts
> +	selector: 'login',
Don't forget to add app prefix to all comonent/directive/pipe selectors in your app.
If I'm not mistaken Angular CLI does this automatically but maybe something is configured incorrectly in the camp boilerplate (or in you project).
```suggestion
	selector: 'camp-login',
```

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/login/login.component.ts
> +	selector: 'login',
Please, check other components as well. App prefix is missing there as well.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +<div class="registration">
As I've already mentioned in my other comment we can apply styles to the `:host` selector.
It will help us to reduce nesting in the template and increase code readability.
You can find details about `:host` selector in the Angular [docs](https://angular.io/guide/component-styles#host).

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +            <input matInput formControlName="email">
Let's add `type="email"` [attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) to improve UX. Don't forget to add correct 'type' attribute for input elements where possible:
```suggestion
            <input matInput formControlName="email" type="email">
```

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +            <input matInput formControlName="email">
I've noticed similar code in other components as well. Don't forget to apply the change there as well.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +        <a class="registration__login-link" routerLink="/login">Sign in</a>
I'm not sure about the UI and how it looks but are you sure it's a good idea to display the error between two buttons?
Probably move this error above the 'Sign up' button.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +	retypePassword: FormControl<string>;
Let's add `readonly` access modifier for properties.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +	protected readonly formGroup: FormGroup<RegistrationFormControls>;
Please, adjust JSDoc. If I'm not mistaken we have a 'registration' for here.

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/core/interceptors/authentication.interceptor.ts
> +			map(_ => this.addAuthentication(request)),
```suggestion
			map(() => this.addAuthentication(request)),
```

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/login/login.component.ts
> +		}
Try to click 'submit' button without touching form fields first. Form won't be submitted but you won't see any feedback for your action in the UI. No errors will be displayed to you.
To handle such cases we have to touch all form controls programmatically. Luckily Angular FormGroup has `markAllAsTouched` method. We can use it like this:
```suggestion
	protected handleSubmit(): void {
	        this.formGroup.markAllAsTouched();
		if (this.formGroup.invalid) {
			return;
		}
```

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/login/login.component.ts
> +	}
As far as I can see it will be more convenient if we just return an Observable here. So we can omit 'of' operator in 'catchApiError'.
RxJS `EMPTY` can help us. It can be used here like this:
```suggestion
	private catchLoginError(apiError: ApiError): Observable<void> {
		this.formGroup.setErrors({
			login: apiError.errorMessages.join(' '),
		});
		return EMPTY;
	}
```

`EMPTY` will complete the stream. It's expected behavior when we have an error.
You can read more about it [here](https://www.learnrxjs.io/learn-rxjs/operators/creation/empty).

2023-09-06 06:59 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/login/login.component.ts
> +			catchApiError(apiError => of(this.catchLoginError(apiError))),
'catchApiError' name indicates a breach between app abstraction layers.
Component is View layer and API client is Domain layer.  Layers are isolated and can only communicate via its closest relative. You can read about it our [wiki](https://wiki.saritasa.rocks/frontend/frameworks/architecture/).
So usually components should not catch/handle API errors directly. We prefer to transform API error to something like AppError which can be handled by the component.

2023-09-06 09:27 UTC, shalomich commented on apps/angular/src/app/features/auth/login/login.component.spec.ts
I am sorry, I marked as resolved because I deleted tests for registration component but didn't forget for login component

2023-09-08 06:37 UTC, danilkukryakov requested changes

2023-09-08 06:37 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/login/login.component.ts
> +		this.authService.login({
Usually we don't add errors in the return type of the function. So I would expect `login` method from AuthService to look like this:
```ts
public login(loginModel: Login): Observable<void> {
  // ...
}
```

As I can see you have `catchApiError` operator which takes error, then converts it to a value and then emits it.
I don't think such workflow is good as we should not convert stream errors to stream values.
RxJS stream has different workflow for values and errors, and it's better not to mix them.

You can easily fix it by adjusting `applicationApiErrorHandler` utility. You can use `throwError` operator:
```ts
export function applicationApiErrorHandler(apiError: ApiError): Observable<AppError> {
	const appError = AppErrorMapper.fromApiError(apiError);
	return throwError(() => appError);
}
```

However, this won't work until we make some adjustments to `AppError` class.
To create our custom errors we have to extend JS `Error` class:
```ts
export class AppError extends Error {
	// ...

	public constructor(errorMessages: readonly string[]) {
		super();
		// ...
	}
}
```

After these changes error handling flow will be more explicit and clear.

2023-09-08 06:37 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +			retypePassword: formData.retypePassword,
If I'm not mistaken 'register' method from AuthService doesn't require `retypePassword` property.
I mean usually we ask user to enter his password twice just to make sure there are no typos in it.
We don't need to send both password and retypePassword to the server (as backend accepts only single password property).

We need `retypePassword` only inside the registration form. We use it to run validation and show errors to user.
Thus this property is redundant outside the component and we don't have to pass it to API service.
Please, adjust this workflow.

2023-09-08 06:37 UTC, danilkukryakov commented on apps/angular/src/core/interceptors/authentication.interceptor.ts
> +			request.url === this.apiUriBuilder.buildRefreshUri();
Let's move this logic to 'ApiUriBuilder'. My suggestion will be to make something like this:
```suggestion
		return this.apiUriBuilder.getAuthUrls().includes(request.url);
```

Alternatively you can use `startsWith` utility if all Auth urls have the same prefix:
```suggestion
		return request.url.startsWith(this.apiUriBuilder.getAuthBaseUri());
```

2023-09-08 06:37 UTC, danilkukryakov commented on apps/angular/src/core/interceptors/http-interceptor-provider.ts
> +export const httpInterceptorProvider = [
```suggestion
export const httpInterceptorProvider: Provider[] = [
```

2023-09-08 06:37 UTC, danilkukryakov commented on apps/angular/src/core/services/auth.service.ts
> +	private readonly tokenStorageService = inject(TokensStorageService);
In real projects we usually have multiple tokens in the storage. That's why we prefer to create a service to encapsulate interaction with localStorage.
It seems like you have such service as it's called TokensStorageService.
However, as I can see from the implementation Token**s**StorageService can only work with a **single** token. (maybe name is a bit misleading as you store two user tokens as single localStorage entity).

It's not a big issue for now as most likely we won't need to use localStorage for anything other than saving user access token. So first solution I may suggest is to simply rename TokensStorageService to `UserAccessTokenStorageService`.
However, a better solution will be to adjust TokensStorageService to make it responsible for working with localStorage, so we can save other values there other than user access tokens.

2023-09-08 06:37 UTC, danilkukryakov commented on apps/angular/src/core/services/auth.service.ts
> +	private readonly tokenStorageService = inject(TokensStorageService);
Also note that it's recommended to add app prefix to your localStorage tokens.
We usually have multiple Angular projects and they all run on localhost:4200. So localStorage data from different projects might be conflicting. That's why we prefer to app project prefix to all localStorage keys.

2023-09-08 08:23 UTC, shalomich commented on apps/angular/src/app/features/auth/login/login.component.css
> +  text-align: justify;
Yes. It gives me desired UI.

2023-09-08 09:57 UTC, shalomich commented on apps/angular/src/app/features/auth/login/login.component.html
> +    </mat-form-field>
It is good idea but according for requirement current solution is enough

2023-09-08 10:10 UTC, shalomich commented on apps/angular/src/core/services/auth.service.ts
> +	private readonly tokenStorageService = inject(TokensStorageService);
I will rename service to UserAccessTokenStorageService because now it is enough for current task. But probably I will change it in nex PRs.

2023-09-08 11:57 UTC, danilkukryakov approved these changes
You've made good progress working of the improvements. Well done!
Please, see my comments below and resolve them.
After you resolve all of them you can merge your PR. Feel free to ping me in Slack if you have any questions.

2023-09-08 11:57 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/login/login.component.ts
> +			catchError((error: unknown) => this.catchLoginError(error)),
For catching AppErrors in the component we can create a custom RxJS operator.
It might look like this:
```ts
// catch-app-error.ts
export function catchAppError<T, V>(
  selector: (error: AppError) => ObservableInput<V>,
): MonoTypeOperatorFunction<T | V> {
  return catchError((error: unknown) => {
    if (isAppError(error)) {
      return selector(error);
    }
    return throwError(() => error);
  });
}
```

```ts
// login.component.ts
.pipe(
  tap(() => this.router.navigate([''])),
  catchAppError(error => /* .. */), // 'error' is AppError here.
)
```

It will help us to avoid catching unintended errors. For instance 'this.router.navigate' might trigger some errors unrelated to AppError. Your current implementation just ignores such errors end there is no way to detect them.
With `catchAppError` operator we can handle our AppErrors and still be able to handle other unexpected errors if we need.

2023-09-08 11:57 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +        <mat-error class="registration-form__error" *ngIf="formGroup.controls.email.hasError('email')">{{'Must have an email format'}}</mat-error>
String interpolation is redundant here we can omit it.
```suggestion
        <mat-error class="registration-form__error" *ngIf="formGroup.controls.email.hasError('email')">Must have an email format</mat-error>
```

2023-09-08 11:57 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +        <mat-error class="registration-form__error" *ngIf="formGroup.controls.email.hasError('email')">{{'Must have an email format'}}</mat-error>
Please, check this in other components as well. There are several places with similar redundant string interpolation.

2023-09-08 11:57 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +		if (isAppError(error)) {
As I've mentioned in my other comment we can create `catchAppError` operator to simplify errors handling in the components.
Let's use this operator here as well. It will help us to eliminate code duplication.

2023-09-08 11:57 UTC, danilkukryakov commented on apps/angular/src/core/guards/auth.guard.ts
> +		router.navigate(['auth']);
We can improve this code a bit. Look closely to return type of 'CanActivateFn'.
It should return either `boolean` or `UrlTree`.
`UrlTree` is used in guards to perform redirects, that's exactly what we need here.
To convert 'string' to `UrlTree` you can use 'parseUrl' utility from Router.

```suggestion
		return () => router.parseUrl('auth');
```

2023-09-08 11:57 UTC, danilkukryakov commented on apps/angular/src/core/guards/auth.guard.ts
> +export function shouldBeAuthenticatedGuard(): CanActivateFn {
We can adjust implementation of this function to make it a bit simpler.
Instead of returning CanActivateFn let's make 'shouldBeAuthenticatedGuard' an activation function.
You will look like this:
```ts
export const shouldBeAuthenticatedGuard: CanActivateFn = () => {
  // ...

  return isAuthenticated;
}
```

Such approach is better because CanActivateFn has some arguments which can be used to determine whether route can be activated or not.

2023-09-08 11:57 UTC, danilkukryakov commented on apps/angular/src/core/guards/auth.guard.ts
> +export function shouldBeNotAuthenticatedGuard(): CanActivateFn {
Let's rewrite this guard as well, see my other comment for reference.

2023-09-08 11:57 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +			retypePassword: ['', [Validators.required, ApplicationValidators.retypePassword(passwordControl)]],
Form fields cross validation is always tricky. It's not easy to implement it right.
If I'm not mistaken your implementation doesn't cover all cases.
For example, try to do the following:
1. Enter '12345' to password field
2. Enter '123456' to retypePassword field
3. See an error below retypePassword field
4. Enter '123456' in password field (so both fields have the same value now)

Actual behavior: Error is still displayed below retypePassword.
Expected behavior: No error should be displayed.

I don't think it's an important thing that we should fix no matter what. So you can leave this as is and fix it later.
A simple solution is to use Form validator instead of FormControl one. It means the whole form is validated instead of single controls. This solution is still suboptimal though as it has some drawbacks.

Anyway, it's up to you whether you want to implement it or not. Mark my comment as 'Resolved' if you think current behavior is acceptable.

2023-09-08 11:57 UTC, danilkukryakov commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +    <a class="registration-form__login-link" routerLink="/auth/login">Sign in</a>
Cool thing about Angular Material buttons - you can apply them to both `button` and `a` elements.
So we can get a nicer UI by providing `mat-button` directive to this link:
```suggestion
    <a mat-button class="registration-form__login-link" routerLink="/auth/login">Sign in</a>
```

Maybe it's not relevant and the UI is already good. Then mark my comment as 'Resolved'.

2023-09-08 15:09 UTC, shalomich commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +    <a class="registration-form__login-link" routerLink="/auth/login">Sign in</a>
I specifically did not use mat-button to make it more obvious that this is a link.

2023-09-09 09:25 UTC, merged