Feature/jc 558 anime details
saritasa-nest/camp-js-2023-roman-simernin pull request #13
Opened 2023-09-23 12:48 UTC by shalomich

2023-09-23 22:05 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details/image-modal/image-modal.component.html
> +<img [src]="imageModelData.imageUrl" [alt]="">
Why `alt` is empty?
You can add alt

2023-09-23 22:05 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +		return this.sanitizer.bypassSecurityTrustResourceUrl(youtubeTrailerUrl);
```suggestion
		const youtubeTrailerUrl = `https://www.youtube.com/embed/${youtubeTrailerId}`;
		return this.sanitizer.bypassSecurityTrustResourceUrl(youtubeTrailerUrl);
```

2023-09-23 22:05 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime-service.ts
> +import { catchApiError } from '../utils/rxjs/catch-api-error';
```suggestion
import { AnimeParametersMapper } from '@js-camp/core/mappers/anime/anime-parameters.mapper';
import { PaginationMapper } from '@js-camp/core/mappers/pagination.mapper';
import { AnimeDetailsMapper } from '@js-camp/core/mappers/anime/anime-details.mapper';
import { AnimeDetails } from '@js-camp/core/models/anime/anime-details';
import { AnimeDetailsDto } from '@js-camp/core/dtos/anime/anime-details.dto';

import { catchApiError } from '../utils/rxjs/catch-api-error';
```

2023-09-24 08:33 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-details/image-modal/image-modal.component.html
> +<img [src]="imageModelData.imageUrl" [alt]="">
I was guided by this link from @danilkukryakov  https://www.w3.org/WAI/tutorials/images/decision-tree/. Or can I set "Full size anime cover" in alt attribute?

2023-09-24 08:34 UTC, shalomich commented on apps/angular/src/app/app-routing.module.ts
> +		component: PageNotFoundComponent,
Got it.

2023-09-25 03:26 UTC, andrey-gazzaev requested changes

2023-09-25 03:26 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +            </div>
This code seems to be repeated a lot. Let's separate it into a separate component, plus you can use `article`.

2023-09-25 03:26 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.css
> +.anime-info-item__space {
It looks like a `separator`

2023-09-25 03:26 UTC, andrey-gazzaev commented on libs/core/dtos/anime/anime-airing.dto.ts
> +}
Are you sure this data model only applies to anime? Or it can be used anywhere there is some time/date `range`

2023-09-25 03:26 UTC, andrey-gazzaev commented on libs/core/mappers/anime/anime-details.mapper.ts
> +			status: dto.status.replace(/_/g, ' '),
Looks like `status` is a `enum`, so let's use it.

2023-09-25 03:26 UTC, andrey-gazzaev commented on apps/angular/src/shared/pipes/empty.pipe.ts
> +	private readonly emptyReplacement: string = '-';
```suggestion
	private readonly emptyReplacement = '-';
```

2023-09-25 03:26 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +			tap(animeDetails => this.excludeAnimeNotFound(animeDetails)),
It looks like you are simulating a `catchError` operation. I can suggest you to make the solution consistent.

2023-09-25 03:26 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-cover-modal/anime-cover-modal.component.ts
> +	/** Image url. */
```suggestion
	/** Image URL. */
```

2023-09-25 04:33 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/image-modal/image-modal.component.html
> +<img [src]="imageModelData.imageUrl" [alt]="">
Smartly here you need a detailed description of the image, the type of what is there, etc. This data should be provided by `BE`. If you write a text like `Big picture`, you can imagine the face of a person who physically cannot see the `Big picture`.

2023-09-25 04:34 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/image-modal/image-modal.component.html
> +<img [src]="imageModelData.imageUrl" [alt]="">
Therefore, in this case it is better to leave the alternative text blank

2023-09-25 05:31 UTC, shalomich commented on libs/core/dtos/anime/anime-airing.dto.ts
> +}
Now it is used only for anime. After if it will need I will create separate DTO for date range.

2023-09-25 06:10 UTC, shalomich commented on libs/core/mappers/anime/anime-details.mapper.ts
> +			status: dto.status.replace(/_/g, ' '),
We usually use enum for business logic when there is anyone condition by enum value. But here it is plain string only for view. What do you think about?

2023-09-25 06:23 UTC, andrey-gazzaev commented on libs/core/mappers/anime/anime-details.mapper.ts
> +			status: dto.status.replace(/_/g, ' '),
The issue is consistency of solutions and ease of extension. Imagine you need to make a filter by status. How much time will you spend if you assume that the same data structure has different implementations? Imagine the surprise of another developer who is used to the fact that if he sees an enumeration, he will expect a certain implementation. Otherwise, the developer will have "Why?" questions.

2023-09-25 07:19 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-details/image-modal/image-modal.component.html
> +<img [src]="imageModelData.imageUrl" [alt]="">
Got it.

2023-09-26 02:50 UTC, andrey-gazzaev approved these changes

2023-09-26 02:50 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +			<camp-anime-info-item title="Type" [value]="animeDetails.type | titlecase" />
It looks like your `title` attribute is overriding its own `title` attribute. You can check this by hovering the cursor over the block

2023-09-26 02:50 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +		this.dialog.open(AnimeCoverModalComponent, { data: modalParameters });
```suggestion
		this.dialog.open(AnimeCoverModalComponent, { data: { imageUrl }});
```

2023-09-29 09:31 UTC, timofei-maximov-saritasa approved these changes

2023-09-29 09:31 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +		<div>{{ animeDetails.description }}</div>
If you are into semantics here, then let's use `<p>` over `<div>`

2023-10-02 11:50 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +			(click)="openFullSizeImage(animeDetails.imageUrl)"
It's better to avoid 'click' event handlers on non-clickable elements.
Usually we add 'click' event handler only on `button` element for the following reasons:
- Semantics
- Accessible UI and UX out of the box (outline, keyboard accessibility, etc.)

I suppose it might be possible to wrap this image into a button. Alternatively you can add a button above the image.
In my opinion, the best solution will be the second option: add button with magnifying glass icon in the bottom right corner (or other place). I think, it will be quite straightforward for user.
By the way, your current solution hide such feature from user. As there is no indicator in the UI that anime cover can be clicked.

2023-10-02 11:50 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +		this.dialog.open(AnimeCoverModalComponent, { data: modalParameters });
You can improve type safety of this code and get hints from IDE about dialog params:
```suggestion
		this.dialog.open<AnimeCoverModalComponent, AnimeCoverModalParameters, void>(
			AnimeCoverModalComponent, { data: modalParameters }
		);
```

`open` method has three generic type params:
- `T` - dialog component (AnimeCoverModalComponent in your case)
- `D` - dialog options, i.e. properties provided in 'data' option (AnimeCoverModalParameters in your case)
- `R` - dialog result, i.e. 'afterDialogClosed()' return type ('void' in your case as dialog doesn't return anything)

Please, prefer to declare these types everywhere when you have a dialog. Otherwise you will end up with 'any'.

2023-10-02 11:50 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-info-item/anime-info-item.component.html
> +<article class="anime-info-item">
I don't think, 'article' usage is reasonable here. In my opinion it's redundant and we can reduce code nesting by omitting it. Styles from 'anime-info-item' can be applied to `:host` selector directly.

2023-10-02 11:50 UTC, danilkukryakov commented on apps/angular/src/shared/pipes/empty.pipe.ts
> +	pure: false,
It's better to set 'pure' to `true` (its default value). It is better for performance as pipe. Pure pipe means:
> `transform()` method is invoked only when its input arguments change. Pipes are pure by default.
So it's better to omit this param and use pure pipe:
```suggestion
```

2023-10-02 11:50 UTC, danilkukryakov commented on apps/angular/src/shared/pipes/empty.pipe.ts
> +	pure: false,
By the way, 'pure' option JSDoc suggests use cases for 'false' option:
> If the pipe has internal state (that is, the result depends on state other than its arguments), set pure to false. In this case, the pipe is invoked on each change-detection cycle, even if the arguments have not changed.

According to your implementation it's not relevant as your pipe doesn't have internal state.

2023-10-02 11:50 UTC, danilkukryakov commented on libs/core/dtos/anime/anime-airing.dto.ts
> +	readonly end: string;
If you have date represented as string in DTO then provide date format in the JSDoc. It will give other developers are hint how the value should be mapped.
It's useful as we might have date in different formats, e.g. yyyy-MM-dd'T'HH:mm:ss, yyyy-MM-dd, MM/dd/yyyy, dd/MM/yyyy etc.

2023-10-02 11:50 UTC, danilkukryakov commented on libs/core/mappers/anime/anime-status.mapper.ts
> +	}
You have similar interface called AnimeTypeMapping. I guess, you will have more such mappings in the future.
So let's create a utility type to avoid code duplication.
It might look like this:
```ts
interface EnumMapping<TDto, TModel> {
		readonly model: TModel;
		readonly dto: TDto;
}

type AnimeStatusMapping = EnumMapping<AnimeStatusDto, AnimeStatus>;
```

2023-10-02 11:50 UTC, danilkukryakov commented on libs/core/models/anime/anime-details.ts
> +	readonly airedStartDate: Date;
Please, adjust JSDoc.

2023-10-02 11:50 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +		const youtubeTrailerUrl = `https://www.youtube.com/embed/${youtubeTrailerId}`;
Maybe we should store youtube URL (https://www.youtube.com/embed/) somewhere in our config.
Alternatively you can create a utility function to build URL for embedded YouTube video.

2023-10-02 11:50 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +			<camp-anime-info-item title="Genres" [value]="animeDetails.genreNames.join(', ') | empty" />
I think you can create a custom pipe for '.join'. It will look cleaner.

2023-10-02 11:50 UTC, danilkukryakov commented on libs/core/models/anime/anime-details.ts
> +	readonly airingStatus: boolean;
It's a bit confusing why 'airing**Status**' doesn't have any statuses inside it.
For boolean properties we usually add `is` prefix. So I think we can rename this property to `isAiring` (or something similar).
Don't forget to update JSDoc as well.

2023-10-02 11:50 UTC, danilkukryakov commented on libs/core/models/anime/anime-details.ts
> +export interface AnimeDetails {
If I'm not mistaken you have a model here, not DTO. Please, adjust JSDoc.

2023-10-02 11:50 UTC, danilkukryakov commented on apps/angular/src/core/services/api-uri-builder.ts
> +	public buildGetAnimeByIdUri(id: number): string {
As far as I can see your solution was good when we have small amount of API endpoints. As we have more endpoints it is harder to maintain them using your solution.
Let's analyze possible options for refactoring. You can get some inspiration from [here](https://github.com/saritasa-nest/saritasa-frontend-boilerplate-angular/blob/develop/projects/common/src/lib/core/services/app-urls.config.ts) but I encourage you to adjust your current solution rather than using suggested one as is.

2023-10-02 11:50 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.css
> +  max-height: var(--anime-thumbnail-image-size);
If you adjust size of the image it might be distorted.
To avoid it you can try to use `object-fit` CSS [property](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit).

2023-10-02 11:50 UTC, danilkukryakov commented on libs/core/dtos/anime/anime-details.dto.ts
> +	readonly modified: string;
I know it's debatable but it's not mandatory to declare all properties from backend in our DTOs.
In some cases (like this one) we don't use all properties provided by API. So we might omit them in DTO.
We can always add them when they will be necessary.

2023-10-05 10:30 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.css
> +  max-height: var(--anime-thumbnail-image-size);
May I just use width and height insead max-width and max-height?

2023-10-05 10:47 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.css
> +  max-height: var(--anime-thumbnail-image-size);
Yes, I think you should try it. If it looks good then such solution might be used.

2023-10-05 18:48 UTC, dmitrymaslov13 approved these changes

2023-10-06 09:37 UTC, danilkukryakov approved these changes
I don't know whether you have some requirements about UI quality but anyway.
I encourage you to invest some time and improve user interface of your app.
According to preview it looks like all feature requirements are met. However, as a user I would be confused if I saw your app somewhere.
An important part of frontend developer job is making the user interface appealing to user. It means it should look good and provide good user experience.
'look good' seems like a subjective term. Nevertheless, big companies liлу Apple or Google have design guidelines for good UI which was tested on large amount of users for years. So their UI solutions are considered good in most cases.
That's why we try to base our UI on some design system. So UI elements are consistent and look pretty to user. There are several approaches to achieve this - the easiest is using a ready-made UI components system.
There are several UI components systems for Angular. Most popular are [Angular Material](https://material.angular.io/), [NG-Bootstrap](https://ng-bootstrap.github.io/#/home), [PrimeNG](https://primeng.org/), etc.
In our projects we usually stick with Angular Material. That's why we include it as a dependency in our Angular boilerplate.
So I recommend you to analyze how to improve user interface design of your app using Angular Material components (card, button, icon, toolbar and others). You may do this as a separate PR.

2023-10-06 09:37 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.css
> +  content: url("../../../../assets/magnifying-glass.svg");
Usually we don't work with icons in Angular like this.
If we have Angular Material in our project then we can use 'mat-icon' element in most cases.
It uses [Google Material Icons](https://fonts.google.com/icons?selected=Material+Icons+Outlined) font under the hood.
```html
<mat-icon>zoom_in</mat-icon>
```
In your case [zoom_in](https://fonts.google.com/icons?selected=Material+Icons+Outlined:zoom_in:&icon.set=Material+Icons&icon.query=zoom+in) icon will fit.
It work especially good in combination with `mat-icon-button` [component](https://material.angular.io/components/button/api#MatIconButton).
```html
<button
  mat-icon-button
  type="button"
  (click)="onClose()"
>
  <mat-icon>close</mat-icon>
</button>
```

Alternative approach is using [MatIconRegistry](https://material.angular.io/components/icon/overview) for custom SVG icons. In this case we will need to create an additional service for managing custom icons.
In my opinion, this approach is an overhead in your case. Icons from Google Material icons set should be enough.

2023-10-06 09:37 UTC, danilkukryakov commented on apps/angular/src/shared/pipes/comma-join.pipe.ts
> +	}
We can improve this pipe:
1. Let's allow any joiner for array elements. We can pass it as pipe argument.
2. Improve type safety of pipe. We can restrict our pipe to work with arrays at compile time instead of runtime.

My suggestion looks like this but you can adjust it as needed:
```suggestion
@Pipe({
	name: 'join',
})
export class JoinPipe implements PipeTransform {

	/** @inheritdoc */
	public transform<T>(value?: readonly T[], joiner = ', '): string {
		if (value) {
			return value.join(joiner);
		}

		return '';
	}
```
You can provide pipe argument like this:
```html
{{ items | join }}
{{ items | join: '|' }}
```
More about Angular pipes you can find [here](https://angular.io/guide/pipes).

2023-10-06 09:37 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +		></iframe>
It looks like we can create a separate component for displaying YouTube video.
In this case we can reuse it in other places of our app. Besides, we can encapsulate logic related to YouTube url building in such component.
```suggestion
		<camp-youtube-player [videoId]="animeDetails.youtubeTrailerId" />
```

2023-10-06 09:37 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-info-item/anime-info-item.component.css
> +  margin: 0 0.4em;
You should be careful with font related units (em and rem). In some cases 'em' might bring unexpected behaviour because size is relative to parent element font size. Sometimes `rem` might be a better alternative as size is relative to page root element instead.
I'm not sure how you use this 'anime-info-item-separator'. So if in your case everything looks as expected then mark my comment as 'Resolved'.

2023-10-07 11:01 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-details/anime-info-item/anime-info-item.component.css
> +  margin: 0 0.4em;
I use separator for this. I found its in Internet. Maybe there is better solution but for me it works as expected.
<img width="529" alt="image" src="https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/75197645/6be2a10f-97d5-4f9b-a0e7-e8a20aee5edc">

2023-10-07 12:02 UTC, merged