Feature/jc 568 anime management
saritasa-nest/camp-js-2023-roman-simernin pull request #14
Opened 2023-11-09 07:30 UTC by shalomich

2023-11-09 08:01 UTC, golovachev-yaroslav approved these changes

2023-11-09 08:15 UTC, shalomich commented
Don't worry half of the files are models and mappers)

2023-11-09 08:17 UTC, shalomich commented
@danilkukryakov I will refactor the styles of anime details in separate PR

2023-11-14 15:43 UTC, andrey-gazzaev requested changes
I'm glad you were able to open a PR. Way to go!

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +		<div class="anime-card__image-container">
It looks like you didn't add a header to this section. If this doesn't fit your design, you can use a [utility class](https://allyjs.io/tutorials/hiding-elements.html#how-to-hide-elements-visually) to hide the content from the user, but not from the screen reader.

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +			<p class="anime-card-info__description typography typography_body" *ngIf="animeDetails.description !== ''" >{{ animeDetails.description }}</p>
It looks like you have something wrong with the code alignment. Let's fix it. If you have any problems with prettier or eslint, you can write to me and we'll figure it out together.

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +	 * Get genre names.
```suggestion
	 * Gets genre names from specified anime details
```

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +	protected getGenreNames(animeDetails: AnimeDetails): readonly string[] {
```suggestion
	protected getGenreNames(animeDetails: AnimeDetails): string[] {
```

There is no need to describe the return type as readonly. Usually readonly is used as a helper when writing pure functions. For example, we specify readonly for an array in parameters so that we can't change an incoming parameters inside function. The same is true for an object.

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +		)
```suggestion
		dialogRef.afterClosed().pipe(
		  filter(isDeletionConfirmed => isDeletionConfirmed),
			switchMap(() => this.deleteAnime(id)),
			takeUntilDestroyed(this.destroyRef),
		)
```

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-info-item/anime-info-item.component.css
> +  font-family: "Anime Ace", sans-serif;
@shalomich Often the same types of typography are used on projects. I would recommend you to create a separate file with typography classes. For example:
```css
.body-1 {
  font-family: "Times New Roman", Times, serif;
  font-size: 14px;
  font-style: normal;
  font-weight: 400;
  ...
}
```

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-management/anime-creation/anime-creation.component.ts
> +		forkJoin({
It is strange to see how a component that is designed only to collect information from the user knows that some data may not exist and needs to be created.

Let's transfer the logic from `forkJoin` to the domain level.

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-management/anime-editing/anime-editing.component.ts
> +		forkJoin({
By the way `combinelatest` is not suitable for this purpose? Then you are renaming the fields of the object and it looks cluttered and makes it difficult to read the code.

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.html
> +        <mat-form-field class="anime-form-section__field" *ngIf="formGroup.controls.englishTitle as englishTitle">
```suggestion
        <mat-form-field 
          *ngIf="formGroup.controls.englishTitle as englishTitle"
          class="anime-form-section__field"  
        >
```

Try to write structural directives at the beginning of tag attributes.

2023-11-14 15:43 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.ts
> +		});
```suggestion
		this.formGroup = this.formBuilder.group<AnimeManagementFormControls>({
			englishTitle: this.formBuilder.control('', Validators.required),
			...
		});
```

Use `formBuilder.control`. In addition, let's put the form initialization in a separate file.

2023-11-15 10:43 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-details/anime-info-item/anime-info-item.component.css
> +  font-family: "Anime Ace", sans-serif;
I'm using typography here, but I forgot to remove this duplicated property for the font family

2023-11-15 11:22 UTC, golovachev-yaroslav approved these changes

2023-11-16 03:35 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +				(click)="openFullSizeImage(animeDetails.imageUrl)">
```suggestion
			<button 
			  type="button"
				mat-icon-button
				class="anime-card__image-full-size-btn" 
				(click)="openFullSizeImage(animeDetails.imageUrl)"
		  >
```

2023-11-16 03:35 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +			.subscribe();
```suggestion
		this.dialog.open<ConfirmationModalComponent, ConfirmationModalParameters, boolean>(ConfirmationModalComponent, {
			data: {
				confirmationText: 'Are you sure you want to delete this anime?',
			},
		})
		.afterClosed()
		.pipe(
			filter(isDeletionConfirmed => isDeletionConfirmed),
			switchMap(() => this.deleteAnime(id)),
			takeUntilDestroyed(this.destroyRef),
		)
			.subscribe();
```

2023-11-16 03:35 UTC, andrey-gazzaev commented on libs/core/mappers/anime/anime-form-data.mapper.ts
> +}
This is a good approach. I suggest extending it to mapping a UI model to a domains model.

2023-11-16 03:35 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime-form.service.ts
> +	private createOrGetGenres(formData: AnimeFormData): Observable<number[]> {
Are you sure the name of the function conveys the full meaning of what is going on in it? I can infer from the name that I will either create or return entities. But judging from the code, they will be returned either way. I think the word create reveals the internal implementation of the function, and we have an open abstraction.

2023-11-16 03:35 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime-multiple-autocomplete.service.ts
> +		}
Imagine if you have 5 or 10 selects and you use this service for that, how much logic will grow? Your approach with `MultipleAutocompleteService` is not bad, but with this approach your `AnimeMultipleAutocompleteService` should be designed to configure each of the selects with infinite scrolling

2023-11-16 03:35 UTC, andrey-gazzaev commented on apps/angular/src/core/services/studio.service.ts
> +		const uri = this.apiUriBuilder.buildGetStudioListUri();
URI is not quite the correct term in relation to an API service. Let's use URL

2023-11-16 03:35 UTC, andrey-gazzaev commented on apps/angular/src/shared/components/image-file-uploading/image-file-uploading.component.html
> +    <img class="image-file-preview__image" *ngIf="imageFile$ | async as imageFile; else noImageAvailable" [src]="getImageSource(imageFile)" alt=""/>
```suggestion
    <img 
      *ngIf="imageFile$ | async as imageFile; else noImageAvailable"
       class="image-file-preview__image" 
       [src]="getImageSource(imageFile)" 
       alt=""
     />
```

I've written about this before, try to use structural attributes first. 

For example:
```html
<tag
  *ngIf <- 1st
  class <- 2nd
  etc...
/>
```

2023-11-16 03:35 UTC, andrey-gazzaev commented on apps/angular/src/shared/components/image-file-uploading/image-file-uploading.component.ts
> +	}
What if I don't need to validate this input?

2023-11-19 12:12 UTC, shalomich commented on apps/angular/src/shared/components/image-file-uploading/image-file-uploading.component.html
> +    <img class="image-file-preview__image" *ngIf="imageFile$ | async as imageFile; else noImageAvailable" [src]="getImageSource(imageFile)" alt=""/>
Sorry, I forgot to check it in other components

2023-11-19 12:44 UTC, shalomich commented on apps/angular/src/core/services/studio.service.ts
> +		const uri = this.apiUriBuilder.buildGetStudioListUri();
I don't quite agree with this, but I can do it according to our code convention 
https://www.postman.com/api-glossary/#http:~:text=URIs%20(Uniform%20Resource%20Identifiers)

2023-11-19 12:58 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +			.subscribe();
I use the condition `isDeletionConfirmed === true' due to a compilation error, because isDeletionConfirmed  may be undefined

<img width="493" alt="image" src="https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/75197645/f80d0734-a6a3-408c-a951-a0ee8c1223c7">

2023-11-19 13:27 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.css
> +  gap: var(--space);
But now I only need one space value for all device sizes. Maybe I'll add other spaces when needed?

2023-11-26 11:29 UTC, andrey-gazzaev approved these changes
Good job!

2023-11-26 11:29 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +	<h1 class="anime-details__title typography typography_title">{{animeDetails.englishTitle ? animeDetails.englishTitle : animeDetails.japaneseTitle}}</h1>
```suggestion
	<h1 class="anime-details__title typography typography_title">{{animeDetails.englishTitle != null ? animeDetails.englishTitle : animeDetails.japaneseTitle}}</h1>
```

Please avoid casting types. Also, what if the anime doesn't have a title in any of the languages? Maybe we should make a separate method for generating the title?

2023-11-26 11:29 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +			</button>
Let's add a title to the button, because it's not clear what the button does.

2023-11-26 11:29 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +				filter(isDeletionConfirmed => isDeletionConfirmed === true),
```suggestion
				filter(isDeletionConfirmed => isDeletionConfirmed),
```

2023-11-26 11:29 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.html
> +            <mat-label>English title</mat-label>
Please check the indentation in this file, for some reason you have 4 spaces

2023-11-26 11:29 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.ts
> +			youtubeTrailerId: this.formBuilder.control(null as string | null),
Perhaps you should consider using a regular `FormBuilder`

2023-11-26 11:29 UTC, andrey-gazzaev commented on apps/angular/src/shared/components/confirmation-modal/confirmation-modal.component.html
> +    </button>
Check the indents in this file.

2023-11-26 11:29 UTC, andrey-gazzaev commented on apps/angular/src/shared/components/multiple-autocomplete/multiple-autocomplete.component.ts
> +		this.subscribeToItemAdding();
```suggestion
		this.subscribeToItemAdd();
```

2023-11-26 11:29 UTC, andrey-gazzaev commented on apps/angular/src/theme/variables.css
> +  --space: 20px;
👍

2023-11-26 11:29 UTC, andrey-gazzaev commented on libs/core/mappers/anime/anime-create.mapper.ts
> +export namespace AnimeCreateMapper {
Why separate the creation and editing entities into different files? These functions can reside entirely in the same service or namespace. These functions belong to the same entity, so I don't see the point of separating them.

2023-11-26 11:29 UTC, andrey-gazzaev commented on libs/core/models/anime/anime-create-data.ts
> +	readonly studioIds: number[];
```suggestion
	readonly genreIds: readonly number[];

	/** Studio ids. */
	readonly studioIds: readonly number[];
```

2023-11-26 11:29 UTC, andrey-gazzaev commented on libs/core/models/multiple-autocomplete-item.ts
> +	 * Id.
```suggestion
	 * ID.
```

2023-12-05 13:16 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +				filter(isDeletionConfirmed => isDeletionConfirmed === true),
I can't do this
<img width="599" alt="image" src="https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/75197645/2898f701-4f81-4051-b2c6-52b66fcaf509">

2023-12-06 12:00 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-dashboard/anime-dashboard.component.html
> +    <a routerLink="create" mat-icon-button>
Maybe we have similar problem in other files. Please, check it everywhere.

2023-12-06 12:02 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +	 * Open modal for anime deletion confirmaion.
```suggestion
	 * Open modal for anime deletion confirmation.
```

2023-12-06 12:03 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +	protected openDeletionConfirmation(id: number): void {
To give additional hints about identifiers (or other properties) you can use TypeScript.
```suggestion
	protected openDeletionConfirmation(id: AnimeDetails['id']): void {
```

2023-12-06 12:06 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-editing/anime-editing.component.html
> +</camp-anime-form>
Prefer to use self-closing tags for Angular components without child content:
```suggestion
<camp-anime-form 
  *ngIf="animeFormData$ | async as animeFormData" 
  [animeFormData]="animeFormData" 
  (submitEvent)="editAnime($event)"
/>
```

2023-12-06 12:09 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-editing/anime-editing.component.ts
> +})
I've noticed `changeDetection` property is missing in some components.
By default Angular component has `Default` change detection. It might decrease performance.
That's why we prefer to set `changeDetection` to `OnPush` everywhere.
```suggestion
@Component({
	selector: 'camp-anime-editing',
	templateUrl: './anime-editing.component.html',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
```
Please, add this everywhere.

2023-12-06 12:14 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-editing/anime-editing.component.ts
> +})
By the way, if you create components use Angular CLI you will have this automatically.
Usually we use the following command to create new component:
```bash
npx ng g c anime-editing
```
I'm not sure about NX though, we don't have it in our apps. You may as Pavel Romanov.
It will automatically create required files with correct params. For instance 'camp' prefix will be added automatically as well as 'changeDetection'.

In general it's not recommended to create components/service/pipes/modules/directives automatically. We should generate them using Angular CLI. You can find more details about it in [docs](https://angular.io/cli/generate).

2023-12-06 12:17 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.html
> +                <mat-option *ngFor="let rating of animeRatings; trackBy trackByIndex" [value]="rating">{{rating}}</mat-option>
It's better to avoid variable names shadowing (we have two 'rating' variables here). It decreases code readability.
By the way, *ngIf looks redundant to me, we can inline it:
```suggestion
            class="anime-form-section__field">
            <mat-label>Rating</mat-label>
            <mat-select [formControl]="formGroup.controls.ageRating">
                <mat-option *ngFor="let rating of animeRatings; trackBy trackByIndex" [value]="rating">{{rating}}</mat-option>
```

2023-12-06 12:18 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.html
> +                <mat-option *ngFor="let rating of animeRatings; trackBy trackByIndex" [value]="rating">{{rating}}</mat-option>
We have similar issue in other places, let's fix this everywhere.

2023-12-06 12:21 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.ts
> +	public submitEvent = new EventEmitter<AnimeFormData>();
We prefer to place component's `Input`s and `Output`s at the top of the class.
So component's public interface is visible at the first glance.

2023-12-06 12:22 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.ts
> +		});
Object destruction seems redundant here, we can remove it:
```suggestion
		this.submitEvent.emit(formData);
```

2023-12-06 12:24 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.ts
> +			youtubeTrailerId: this.formBuilder.control(null as string | null),
TypeScript give you warning here because you didn't provide type for FormGroup controls.
Luckily, you have already defined it. So it's quite easy to fix the issue:
```ts
private initAnimeForm(): FormGroup<AnimeManagementFormControls> {
	return this.formBuilder.group<AnimeManagementFormControls>({
		// ...
		youtubeTrailerId: this.formBuilder.control(null),
	});
}
```

2023-12-06 12:25 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.ts
> +			youtubeTrailerId: this.formBuilder.control(null as string | null),
By the way, you will be able to remove type casts in other controls as well (i.e. in imageFile, genres, studios).

2023-12-15 06:10 UTC, danilkukryakov requested changes

2023-12-15 06:10 UTC, danilkukryakov commented on package.json
> +    "xml-js": "^1.6.11",
As far as I can see you don't use 'xml-js' library anymore.
It means we can remove it from our app. Let's do this.

2023-12-15 06:10 UTC, danilkukryakov commented on libs/core/mappers/sorting-parameters.mapper.ts
> +	 */
Fix code indentation here.

2023-12-15 06:10 UTC, danilkukryakov commented on libs/core/mappers/sorting-parameters.mapper.ts
> +	export function toDto<TSortingField>(model: SortingParameters<TSortingField>, sortingFieldMap: Map<TSortingField, string>):
We can increase type safety by restricting generic argument. As far as I can see sort 'field' property should be a `string` type (or literal string type, like `'name'` or `'id'`). According to your implementation we have enum, i.e. union of literal string types.
For examples 'GenreSortingField' sorting will be `'' | 'name' | 'id'`. It's not some random generic type. We know that we always have strings there.
So our generic type can be adjusted like that:
```ts
// sorting-parameters.ts
export interface SortingParameters<T extends string> {
  // ...
}
```
```ts
// sorting-parameters.mapper.ts
export namespace SortingParametersMapper {
	export function toDto<TSortingField extends string>(
		model: SortingParameters<TSortingField>,
		sortingFieldMap: Map<TSortingField, string>,
	): SortingParametersDto {
		// ...
	}
}
```

2023-12-15 06:10 UTC, danilkukryakov commented on libs/core/dtos/s3/s3-params-response.dto.ts
> +	readonly 'success_action_status': string;
Quotes look redundant here, we can omit them:
```suggestion
	readonly policy: string;

	/** Action status. */
	readonly success_action_status: string;
```

2023-12-15 10:16 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-routing.module.ts
> +		canActivateChild: [shouldBeAuthenticatedGuard],
Thanks. It is typo.

2023-12-15 10:41 UTC, shalomich commented on apps/angular/src/core/services/image-file.service.ts
> +export class ImageFileService {
I have to specify `dest` to get s3 parameters. `Dest` can be equal to `Anime image` or `User Avatar`. Both values refer to images, so I named this service as the ImageFileService.

2023-12-15 10:42 UTC, danilkukryakov commented on apps/angular/src/core/services/image-file.service.ts
> +export class ImageFileService {
Ok, sound reasonable to me. Let's leave the name without changes. Thanks for clarifiaction.

2023-12-15 11:03 UTC, shalomich commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.ts
> +		},
I am using the base class (MultipleAutocompleteService) in the MultipleAutocompleteComponent. To use the component, I require the parent component to inject needed inheritor of this service. I wasn't sure if you used this approach, but I decided to give it a try. Your current offer will break the work of this component for me. Alternatively, I can pass Observable<Pagination<MultipleAutocompleteItem> through Input. What do you think about it?

2023-12-15 11:17 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-management/anime-form/anime-form.component.ts
> +		},
I don't see how my suggested solution might break your logic.
AnimeMultipleAutocompleteService still has the same public interface as before. We call public 'getItems' method from the outside as before. Everything should work the same way.

My comment was about overcomplicated  implementation of AnimeMultipleAutocompleteService.
'getProviders' is indeed might be different in MultipleAutocompleteService subclasses. But I don't see any subclasses other than AnimeMultipleAutocompleteService. Are we planning to add more in future?

To be honest, this implementation of autocomplete component is suboptimal. It's good enough for your particular case but it's not scalable. I didn't write any comments about it because I think it's fine overall for your project.
Anyway, there is no need to make it more complex than it should be. If we can implement it without advanced DI features (as I can see we can do so), let's do this in the simplest way possible. Single service injected to component is good (see my example).

2023-12-15 11:23 UTC, shalomich commented on apps/angular/src/core/services/api-url-builder.ts
> +export class ApiUrlBuilder {
I remember your comment from last PR, you already suggested optimizing it, but I think I got the most out of the current implementation. But also on your advice, I use the AppUrlConfig version from the boilerplate in the react tasks. Of course, I can refactor this one in a similar way, but is it worth doing so if this is the last task?

2023-12-15 11:24 UTC, danilkukryakov commented on apps/angular/src/core/services/api-url-builder.ts
> +export class ApiUrlBuilder {
If you refactor it in the react task then we can leave it here without any changes. Mark this comment as 'Resolved' in this case.

2023-12-15 21:36 UTC, shalomich commented on libs/core/models/anime/anime-form-data.ts
> +export interface AnimeFormData {
I need anime form data as a model, rather I need to create a type for form controls.

`export type FormControlsOf<T> = {
	[key in keyof T]: FormControl<T[key]>;
};`

2023-12-18 05:09 UTC, danilkukryakov commented on libs/core/models/anime/anime-form-data.ts
> +export interface AnimeFormData {
It's also a good idea. We use similar utility type in our real projects.

2023-12-25 05:29 UTC, danilkukryakov approved these changes

2023-12-25 05:29 UTC, danilkukryakov commented on libs/core/mappers/anime/anime-form-data.mapper.ts
> +		studioIds: number[];
Let's use readonly arrays here:
```suggestion
		genreIds: readonly number[];
		studioIds: readonly number[];
```

2023-12-25 19:10 UTC, shalomich commented on apps/angular/src/shared/components/multiple-autocomplete/multiple-autocomplete.component.ts
> +		return item.name;
I can't because id can be null

2023-12-25 19:54 UTC, merged