Feature/jc 588 authorization
saritasa-nest/camp-js-2023-roman-simernin pull request #15
Opened 2023-11-23 10:44 UTC by shalomich

2023-11-24 04:15 UTC, golovachev-yaroslav approved these changes

2023-11-24 04:15 UTC, golovachev-yaroslav commented on apps/react/src/api/interceptors/refreshTokenInterceptor.ts
> +import { AxiosError, AxiosResponse, HttpStatusCode } from 'axios';
Let's import external libs firstable, then developer's

2023-11-24 04:15 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/LoginPage/LoginPage.tsx
> +const loginSchema: yup.ObjectSchema<LoginForm> = yup
Let's move validation in a separate file.

2023-11-24 04:15 UTC, golovachev-yaroslav commented on apps/react/src/store/auth/selectors.ts
> +export const selectIsAuthLoading = createSelector(
It's not a good idea to create a selector for every state value. You code will increase.
```
export const selectAuth createSelector(
	(state: RootState) => state.auth,
	state => state,
);
```

`const { isAuthenticated, isLoading, error } = useAppSelector(selectAuth);`

2023-11-26 12:27 UTC, andrey-gazzaev requested changes

2023-11-26 12:27 UTC, andrey-gazzaev commented on apps/react/src/components/AppHeader/AppHeader.module.css
> +.app-header {
```suggestion
.appHeader {
```

2023-11-26 12:27 UTC, andrey-gazzaev commented on apps/react/src/components/Loader/Loader.tsx
> +const LoaderComponent: FC<LoaderProps> = ({ isLoading, children }) => {
```suggestion
const LoaderComponent = ({ isLoading, children } as LoaderProps) => {
```

Don't use react `FC`. This approach has a number of cons. You can familiarize yourself with them in this [article](https://www.totaltypescript.com/you-can-stop-hating-react-fc).

2023-11-26 12:27 UTC, andrey-gazzaev commented on apps/react/src/components/Loader/Loader.tsx
> +
Don't forget to add `displayName` to components. For example: `Component.displayName = 'Component'`. This will make it easier to work with developer tools to react

2023-11-26 12:27 UTC, andrey-gazzaev commented on apps/react/src/features/auth/pages/LoginPage/LoginPage.tsx
> +		</div>
It looks like you have a problem with the layout style of the components. I think you should customize prettier for this.
```suggestion
			<form 
			   onSubmit={handleSubmit(onSubmit)}
				 className={styles['login-form']}
			>
				 <TextField
					  label="Email"
					  error={formErrors.email !== undefined}
					  helperText={formErrors.email?.message}
					  {...register(nameof<LoginForm>('email'))}
				  />
				<TextField
					  type="password"
					  label="Password"
					  error={formErrors.password !== undefined}
					  helperText={formErrors.password?.message}
					  {...register(nameof<LoginForm>('password'))}
					/>
				<Loader isLoading={isLoading} />
				{loginError !== null && <Alert severity="error">{loginError.message}</Alert>}
				<Button type="submit">Sign in</Button>
				<Link 
				    to='/auth/registration' 
				    className={styles['login-form__registration-link']}
				>
				  Sign out
				</Link>
			</form>
		</div>
```

If you have any questions about customization, you can write to me and we will solve them together

2023-11-27 09:15 UTC, shalomich commented on apps/react/src/components/Loader/Loader.tsx
> +		);
I have an error
<img width="532" alt="image" src="https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/75197645/0d46f13c-82b5-4c13-8b95-0c580e060959">

2023-11-27 09:32 UTC, shalomich commented on apps/react/src/components/Loader/Loader.tsx
> +const LoaderComponent: FC<LoaderProps> = ({ isLoading, children }) => {
I have an error 
<img width="653" alt="image" src="https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/75197645/dd331766-45bc-4a11-9c73-b2bc7e29fac6">

2023-11-27 09:33 UTC, shalomich commented on apps/react/src/components/Loader/Loader.tsx
> +const LoaderComponent: FC<LoaderProps> = ({ isLoading, children }) => {
So it works fine
<img width="420" alt="image" src="https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/75197645/65ecd6ba-01dd-4fba-b57a-f75db915ad6d">

2023-11-27 10:56 UTC, andrey-gazzaev commented on apps/react/src/components/Loader/Loader.tsx
> +		);
Remove FC and use `({isLoading, children}: Props) =>`

2023-11-27 11:06 UTC, shalomich commented on apps/react/src/components/Loader/Loader.tsx
> +		);
Same
<img width="650" alt="image" src="https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/75197645/69eca0a9-1ab6-443b-82bc-afa56140e87f">

2023-11-28 02:34 UTC, andrey-gazzaev commented on apps/react/src/components/Loader/Loader.tsx
> +		);
Interesting behavior. Thanks for testing this :) Let's use `<>{children}</>`

2023-11-28 04:13 UTC, andrey-gazzaev approved these changes

2023-11-28 04:13 UTC, andrey-gazzaev commented on apps/react/src/utils/catchApiError.ts
> +	return apiError.type !== undefined && apiError.errors !== undefined;
```suggestion
	return 'type' in apiError && 'errors' in apiError;
```

If you need to check for the existence of some prop in an object, then you can use the `in` operator.

2023-11-28 04:13 UTC, andrey-gazzaev commented on apps/react/src/api/services/authService.ts
> +			));
```suggestion
			const { data: tokensDto } = await http.post<UserAccessTokenDto>(
				AppUrlsConfig.auth.login,
				LoginMapper.toDto(loginModel),
			);
```

2023-12-07 11:23 UTC, timofei-maximov-saritasa commented on apps/react/src/components/AppHeader/AppHeader.tsx
> +AppHeaderComponent.displayName = 'camp-app-header';
displayName is used here because we wrap component with `memo`, devtools will show this component as `camp-app-header`.

![image](https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/86595911/40a97a60-fad3-45b4-af07-59accdff9ecf)

However, if you use this `camp-app-header` it will be hard to find this component inside your code. It is easy to find components if they are associated with the same file name. So let's set  `displayName` to `AppHeader` to avoid this confusion.

![image](https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/86595911/3dad0eeb-1303-49af-90f5-4ab6a754bea4)

2023-12-07 11:23 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/LoginPage/LoginPage.tsx
> +	};
Let's move this outside of component scope

2024-03-25 03:08 UTC, gevorg-gevorgyan-saritasa approved these changes

2024-03-25 06:03 UTC, merged