Feature/jc 518 static book catalog
saritasa-nest/camp-js-2023-roman-simernin pull request #7
Opened 2023-07-08 21:34 UTC by shalomich

2023-07-09 05:13 UTC, andrey-gazzaev approved these changes
Good work!

2023-07-09 05:13 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise1/styles/book-filters.css
> +  padding-left: 56px;
The problem with such comments is that they are hard to maintain, if my `background-position` or `background-size` changes, I have to edit the documentation. And if I'm a new developer and I don't know about this comment, I won't edit it and it will start to lie. 

Let's write these values into variables and calculate the value of `padding-left` through `calc`.

2023-07-09 05:13 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise1/styles/book-filters.css
> +    width: 287.5px;
Same thing about the exact value

2023-07-09 05:13 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise1/index.html
> +        <form class="book-filters-form">
You seem to have missed the heading. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#:~:text=missing%20heading%20is.-,Don%27t%20do%20this%3A,-HTML

2023-07-09 05:13 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise1/index.html
> +  <div class="main-container">
Why don't you use `body` as `main-container`? This would allow you to reduce nesting

2023-07-09 05:13 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise1/index.html
> +</html>
```suggestion
</html>

```

2023-07-09 16:07 UTC, gevorg-gevorgyan-saritasa approved these changes

2023-07-09 16:07 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/exercise1/index.html
> +        <h3 class="subtitle-typography">Filters</h3>
```suggestion
        <h2 class="subtitle-typography">Filters</h2>
```

2023-07-09 16:07 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/exercise1/styles/book-groups.css
> +@media screen and (min-width: 361px) and (max-width: 786px) {
I think `min-width` is not necessary here.

2023-07-09 16:07 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/exercise1/styles/colors.css
> +  --on-primary-color: #fff;
Just for consistency  🌚
```suggestion
  --on-primary-color: #ffffff;
```

2023-07-09 16:07 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/exercise1/styles/typographies.css
> +.body-small-typography {
Can we use `typography` as prefix?

2023-07-09 16:07 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/index.html
> +</html>
```suggestion
</html>

```

2023-07-10 03:34 UTC, daoduong-saritasa approved these changes

2023-07-10 03:34 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/exercise1/styles/book-groups.css
> +  width: 167.2px;
Same with exact value

2023-07-10 03:34 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/exercise1/index.html
> +        <form class="book-filters-form">
You can remove the `form` suffix and it still enough information to indicate this is `book-filters` block

2023-07-10 03:34 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/exercise1/index.html
> +          <div class="book-filter-form__comics-show-field">
```suggestion
          <div class="book-filters-form__comics-show-field">
```

2023-07-10 03:34 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/exercise1/index.html
> +    <footer class="main-container__footer footer-container">
As I see, this two classes have the same meaning. You can remove one and add styles to the other

2023-07-10 03:34 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/exercise1/index.html
> +      <a class="footer-content__top-link top-link body-typography" href="#">Go to top ↑</a>
Same for `top-link` meaning here. I don't see you use it elsewhere, you can remove it for better readability and avoid confusion

2023-07-10 04:12 UTC, golovachev-yaroslav requested changes

2023-07-10 04:12 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise1/styles/typographies.css
> +  --common-font-family: "Inter";
Please add fallback fonts. What if Inter font were loaded? The user should see another font in this case.
Example: `--common-font-family: "Inter", -apple-system, "BlinkMacSystemFont", "Roboto", "Arial", sans-serif;`

2023-07-10 04:12 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.html
> +    <title>JS camp</title>
Why do you remove meta tags, title from `head` ?

2023-07-10 04:25 UTC, timofei-maximov-saritasa approved these changes
Sticky headers are not working:


https://github.com/saritasa-nest/camp-js-2023-roman-simernin/assets/86595911/60456209-c242-4a12-bf65-c843315d3ba2

2023-07-10 04:25 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/exercise1/styles/typographies.css
> +  font-family: var(--common-font-family);
This can be applied to body selector to avoid code duplication.

If you want to stick with this approach, then you can use BEM: each of these items are modifiers

* `typography_subtitle`
* `typography_body`
* etc.

Your typography class may contain `font-family` only common properties across these classes

```html
<div class="typography typography_body>
  hey🤗
</div>
```
https://ru.bem.info/methodology/key-concepts/

2023-07-10 04:25 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/exercise1/styles/book-groups.css
> +  border: 1px solid var(--border-color);
Fyi, there is a pattern for handing image outline
You can use `outline` property. 

```css
/* Color can be changed the way you want.  */
outline: 1px solid rgba(0, 0, 0, 15%);
outline-offset: -1px;
```

2023-07-10 11:26 UTC, shalomich commented on apps/vanilla/src/pages/exercise1/styles/colors.css
> +  --on-primary-color: #fff;
@gevorg-gevorgyan-saritasa Stylelint warn about it and require to simplify

2023-07-10 11:32 UTC, shalomich commented on apps/vanilla/src/pages/exercise1/index.html
> +        <h3 class="subtitle-typography">Filters</h3>
I use `<h2>` for book group titles. I think it has higher priority then filters title. Or is it doesn't matter?

2023-07-10 12:29 UTC, shalomich commented on apps/vanilla/src/pages/exercise1/styles/colors.css
> +  --on-primary-color: #fff;
Also in wiki its'same with stylent warning https://wiki.saritasa.rocks/frontend/languages/css/#dont-be-too-precise:~:text=dark%2Dcolor%3A-,%23000,-%3B%0A%20%20%2D%2Dprimary%2Dlight

2023-07-11 08:16 UTC, golovachev-yaroslav approved these changes

2023-07-11 08:16 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise1/styles/book-filters.css
> +  border-radius: 16px;
It would be better to use var instead of 16px.

2023-07-11 08:16 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise1/styles/book-filters.css
> +  border-radius: 16px;
If it repeats many times.

2023-07-11 08:16 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise1/styles/book-filters.css
> +  }
You can combine(optional)
```
 .book-filters__search-field,
 .book-filters__sort-field {
    width: 288px;
  }
```

2023-07-11 10:45 UTC, golovachev-yaroslav approved these changes

2023-07-11 10:46 UTC, merged