Feature/jc 529 blackjack dice
saritasa-nest/camp-js-2023-roman-simernin pull request #9
Opened 2023-07-19 00:03 UTC by shalomich

2023-07-19 04:14 UTC, andrey-gazzaev requested changes
Great job! Please note the comment below

2023-07-19 04:14 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise2/scripts/domain/blackjack.ts
> +	private gameEndedValue = false;
If property and getter names overlap, `_` can be used to indicate privacy. This is common practice.

2023-07-19 04:14 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise2/scripts/domain/blackjack.ts
> +				}
```suggestion
					player.winStatus = player.totalPoints === winnerPoints;
```

2023-07-19 04:14 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise2/scripts/domain/player.ts
> +	}
As far as I can see these getters and setters are redundant you can just make the properties public

2023-07-19 04:14 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise2/scripts/publishers/currentDiceSidePublisher.ts
> +	currentSide: number;
We are also trying to use `readonly` for properties of interfaces and classes, please do this wherever possible.

2023-07-19 04:14 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise2/scripts/domain/activePlayerLoop.ts
> +		if (this.currentIdex === this.players.length) {
Please do not use [contractions](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions)
```suggestion
		if (this.currentIndex === this.players.length) {
```

2023-07-19 04:14 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise2/scripts/publishers/providedPublisher.ts
> +	private provider: () => T;
Let's also write `type` for `() => T`

2023-07-19 04:14 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise2/scripts/subscribers/winnerPresenter.ts
> +		if (message.winStatus === true) {
```suggestion
		if (message.winStatus) {
```

2023-07-19 04:38 UTC, golovachev-yaroslav requested changes

2023-07-19 07:37 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/exercise2/scripts/createBlackjack.ts
> +	dice = currentDiceSidePublisher;
Is there a reason for this? I don't quite understand why do we need to put `currentDicePublisher` to `dice` variable.

2023-07-19 07:37 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/exercise2/scripts/domain/blackjack.ts
> +		const currentPlayer: Player = activePlayerResult.value;
```suggestion
		const currentPlayer = activePlayerResult.value;
```

2023-07-19 07:37 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/exercise2/scripts/subscribers/playerPointsPresenter.ts
> +	private readonly playerPointsSums: Map<string, number> = new Map<string, number>();
```suggestion
	private readonly playerPointsSums = new Map<string, number>();
```

2023-07-19 08:59 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/exercise2/scripts/publishers/currentDiceSidePublisher.ts
> +	private providedPublisher: ProvidedPublisher<CurrentDiceSide>;
```suggestion
	private readonly providedPublisher: ProvidedPublisher<CurrentDiceSide>;
```

2023-07-19 08:59 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/exercise2/scripts/publishers/playerWinStatusPublisher.ts
> +	playerName: string;
```suggestion
	/** Player name. */
	readonly playerName: string;
```

2023-07-19 13:15 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/exercise2/index.css
> +}
Interesting, I didn't know about that

2023-07-20 18:58 UTC, shalomich commented on apps/vanilla/src/pages/exercise2/index.css
> +}
Typo in first case

2023-07-21 06:47 UTC, golovachev-yaroslav requested changes

2023-07-21 06:47 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise2/index.css
> +  background-color: green;
Please use variables.

2023-07-21 06:47 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise2/index.html
> +  <script defer type="module" src="./index.ts"></script>
It would be better to move script in the bottom of the tab body.
https://qna.habr.com/q/1140328

2023-07-21 06:47 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise2/scripts/domain/dice.ts
> +	private _currentSide: number | undefined;
You can reduce it.
`private _currentSide?: number;`

2023-07-21 06:47 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise2/scripts/domain/dice.ts
> +		return Math.floor(Math.random() * maxValue) + 1;
What is `1` here, could you provide a comment?

2023-07-21 06:47 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise2/scripts/subscribers/createPointsItemElement.ts
> +export function createPointsItemElement(points: number): HTMLLIElement {
I think return type should be `HTMLLIElement`.

2023-07-21 08:30 UTC, shalomich commented on apps/vanilla/src/pages/exercise2/scripts/subscribers/createPointsItemElement.ts
> +export function createPointsItemElement(points: number): HTMLLIElement {
Discuss about it with @golovachev-yaroslav

2023-07-21 08:51 UTC, golovachev-yaroslav approved these changes

2023-07-21 09:43 UTC, dbitkovski approved these changes

2023-07-21 09:54 UTC, daoduong-saritasa approved these changes

2023-07-21 10:09 UTC, merged